### PR TITLE
Adds target "aggregate" property.

### PR DESCRIPTION
**Pull request by dianabarsan**
Adds the optional "aggregate" property to target configuration. 

https://github.com/medic/cht-core/issues/4839

### CODE REVIEW

**Comment by twisteddiana** [comment]
@garethbowen ow, and there's this too. please have a look. Thank you!

**Comment by dianabarsan** [comment]
@garethbowen please have a look at this one, too. Thank you!

**Comment by garethbowen** [comment]
@dianabarsan This seems to be failing on Node 12 and has a merge conflict. Could you have a look please?

**Comment by garethbowen** [comment]
Actually never mind! The rebase fixed it. Merging now.

**Pull request merged**
