### PR TITLE
Ability to persist data between facts when processing nools rules

### PR DESCRIPTION
**Pull request by kennsippell**
medic/medic#5493

Per our discussion yesterday, this is a quick mock up of how we could persist information within nools such that we could calculate Muso's troublesome target. @garethbowen I couldn't find details in nools' docs about "listening" for emitted instances -- but if you have details, I can try that also.  

In the meantime, I'm going to try to build a working version of the target based on this. Interested to see how it handles the corner cases we discussed like editing a family, etc.

### CODE REVIEW

**Comment by abbyad** [comment]
Excited to see how this goes... nothing else to say about the review just yet!

**Comment by SCdF** [comment]
I'm not saying we shouldn't do this, but as couple of general points for consideration:
 - I noticed in my attachment investigation that we probably keep data in nools when we 100% don't need to (I should raise those tickets I know..). So an optimisation may be to drop our in-nools-memory copies of data to reduce RAM usage. This change would stop us from doing that, because when a document changed we wouldn't be able to know if that change required state from a previous incantation of nools (right now it obviously doesn't)
 - If we wanted to run only some rules in some situations and not others (e.g., have some rules run for only some users, or some rules run on the server side and some not), or have some rules run for some contacts and not others (e.g., allows rules to run for online users when loading a particular contact summary) this concept could make that somewhere from confusing to impossible to implement

**Comment by kennsippell** [comment]
@SCdF 

> I noticed in my attachment investigation that we probably keep data in nools when we 100% don't need to (I should raise those tickets I know..).
Check out https://github.com/medic/medic/issues/5515. Feel free to add to it if you have any findings or suggestions.

> So an optimisation may be to drop our in-nools-memory copies of data to reduce RAM usage. 
Would love to chat about how it is possible to completely drop our in-nools-memory copies of the instances.  I think we can drop unnecessary copies of this, but unsure of how to drop this completely. All ears if you have more details to share (text or call welcome).

> e.g., allows rules to run for online users when loading a particular contact summary
Note that this code change does not affect contact summaries.

I would love to split tasks and targets into two different nools flows. Then we could expose this sort of 'persistentStorage' mechanic to targets without implications for server-side tasks. Would that mitigate your concerns?

**Comment by SCdF** [comment]
Targets are probably safer, since at least as I understand them their smallest useful lens into them is at the CHW level (or the supervisor level for supervisor targets, etc etc), which also happens to be the execution level. As opposed to tasks, where you could usefully look at tasks for just one contact. However: people already abuse targets compared to their initial design (again, as I understand it), so I'm not 100% on this.

> But I'm unsure of what our target logic would look like if we drop all copies.

I haven't looked into it so apologies if I'm ignorant, but I presume it's the same as how we generate tasks, which is that we generate the whole shebang at the start, and then whenever a contact or report changes we re-run the rules against just that collection of data and overlay it over whatever we already have. I may be mistaken though!

> Note that this code change does not affect contact summaries.

For sure, I should not have said contact summary, I should have contact page, or something that isn't so overloaded. When you open a contact you see various bits of info, including the tasks for that contact. All tasks are blocked for admin / online users because it's a lot of data, but we could improve our software by allowing tasks to run on contact summaries for all users (we already load all the data over the network to generate the contact summary).

**Comment by kennsippell** [comment]
This is a draft of the the corresponding target would look like. https://github.com/medic/medic-projects/commit/4b5eb91da71f7049b53fe817d5df9156b0536b7b

**Comment by garethbowen** [comment]
@kennsippell Can we delete this now that we have other methods to solve it?

**Pull request closed without merging**
