### PR TITLE
Fix regression to re-enable Node 8 support 

### PR DESCRIPTION
**Pull request by garethbowen**
# Description

Also adds linting to stop this happening again, and unit tests for
this specific function.

#387

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or integration tests where appropriate
- Backwards compatible: Works with existing data and configuration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by garethbowen** [comment]
Review please @dianabarsan 

The most risky part of this is switching out `url.parse` for `new url.URL` because the API isn't identical.

**Review by dianabarsan — COMMENTED** [review]
> The most risky part of this is switching out url.parse for new url.URL because the API isn't identical.

I've been wanting this since 2019: https://github.com/medic/medic-conf/pull/207#discussion_r299917778
Thanks!!

I've scanned the codebase for the API differences between the legacy URL API and WHATWG URL API, and it seems like we're not using any of the missing properties (`auth`, `path`, `query`), while the others seem to be compatible. 

Great work! 

I am seeing a small, problem, however, when I try to use the code to deploy default config: 
Steps:

1. Checkout branch, `npm ci && npm link`. 
2. In ~3.10.x, `cd config/default && npm ci && medic-conf --local`
3. Error on `compile-app-settings… `: 
```
INFO Packaging contact-summary 
INFO Hash: c90b7b233f4e69d95203
Version: webpack 4.41.0
Child
    Hash: c90b7b233f4e69d95203
    Time: 1162ms
    Built at: 03/17/2021 10:27:43
                   Asset      Size  Chunks             Chunk Names
    ./contact-summary.js  68.1 KiB       0  [emitted]  main
    Entrypoint main = ./contact-summary.js
    [0] ./node_modules/moment/moment.js 147 KiB {0} [built]
    [1] /home/diana/projects/medic-conf/src/contact-summary/lib.js 203 bytes {0} [built] [1 warning]
    [2] ./contact-summary.templated.js 15.8 KiB {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
    [4] ./contact-summary-extras.js 15.9 KiB {0} [built]
    [5] /home/diana/projects/medic-conf/src/contact-summary/contact-summary-emitter.js 3.41 KiB {0} [built] [1 warning]
    
    WARNING in /home/diana/projects/medic-conf/src/contact-summary/lib.js
    Module Warning (from /home/diana/projects/medic-conf/node_modules/eslint-loader/dist/cjs.js):
    Failed to load plugin 'node' declared in '../../../medic-conf/.eslintrc': Cannot find module 'eslint-plugin-node'
    Require stack:
    - /home/diana/projects/medic-3100/config/default/__placeholder__.js
    Referenced from: /home/diana/projects/medic-conf/.eslintrc
    
    WARNING in /home/diana/projects/medic-conf/src/contact-summary/contact-summary-emitter.js
    Module Warning (from /home/diana/projects/medic-conf/node_modules/eslint-loader/dist/cjs.js):
    Failed to load plugin 'node' declared in '../../../medic-conf/.eslintrc': Cannot find module 'eslint-plugin-node'
    Require stack:
    - /home/diana/projects/medic-3100/config/default/__placeholder__.js
    Referenced from: /home/diana/projects/medic-conf/.eslintrc
     @ /home/diana/projects/medic-conf/src/contact-summary/lib.js 2:28-64 
ERROR Error: Webpack warnings when building contact-summary
    at /home/diana/projects/medic-conf/src/lib/package-lib.js:103:23
    at finalCallback (/home/diana/projects/medic-conf/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/home/diana/projects/medic-conf/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/home/diana/projects/medic-conf/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/home/diana/projects/medic-conf/node_modules/webpack/lib/Compiler.js:257:39)
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/diana/projects/medic-conf/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/home/diana/projects/medic-conf/node_modules/tapable/lib/Hook.js:154:20)
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/home/diana/projects/medic-conf/node_modules/webpack/lib/Compiler.js:499:39)
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/Compiler.js:298:10
    at /home/diana/projects/medic-conf/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/diana/projects/medic-conf/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
```

It seems like the `.eslintrc` used for `contact_summary` inherits from the main medic-conf one, but somehow the plugin can't be resolved when running . 

Running `../../../medic-conf/src/bin/medic-conf.js --local` yields the same result. 

Adding this:
```
"env": {
    "es6": true,
    "node": true
  },
  "root": true,
```
to both `/src/contact-summary/.eslintrc` and `/src/nools/.eslintrc` fixes it, but I'm unsure if it's the best way forward.

**Comment by garethbowen** [comment]
@dianabarsan Yeah I'm not sure about the `root:true` change either, but I certainly don't expect changes to the root .eslintrc to cascade down to failing the config build. I can't think of any other way around it!

**Review by dianabarsan — APPROVED** [review]
> I certainly don't expect changes to the root .eslintrc to cascade down to failing the config build

Same. It's such a weird side-effect to have had up until now.

**Pull request merged**
